typography_spectrum: 0.15474
color:
  brandColors:
    - '#00cedf'
    - '#ffffff'
    - '#096882'
    - '#54dcec'
    - '#7e9895'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49422
analytics:
  google: null
  facebook: null
  twitter: null
name: Stahle
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: A glimpse in our life (notre vie à Kampala)
    id: 1702bee7-fdc0-413a-9f5e-54cb14a29c64
    type: content
  - name: Our Trips (nos voyages)...
    id: 1102c25b-cba4-4df6-a00a-42b86e0d0cea
    type: content
  - name: About us (les présentations)
    id: f0cf4741-c6fe-4318-9f14-d4e4c5923b83
    type: content
favicon: null
title: 19 Minutes North
purpose: []
